name: church_management_app
description: A church management application for production and worship teams
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.13.0
  provider: ^6.1.1
  flutter_secure_storage: ^9.0.0
  intl: ^0.18.1
  go_router: ^13.0.0
  cupertino_icons: ^1.0.2
  firebase_auth_web: ^5.8.14
  crypto: ^3.0.3
  group_list_view: ^1.0.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  

flutter:
  uses-material-design: true
  assets:
    - assets/COCEPP.png
    - assets/Cocep_.png