// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPCU7dPNxuNX9PK3GH2RIhXkM8gt10pJ4',
    appId: '1:530652435890:web:a0d6ffa87d630d34b540ab',
    messagingSenderId: '530652435890',
    projectId: 'cocep-producccion',
    authDomain: 'cocep-producccion.firebaseapp.com',
    storageBucket: 'cocep-producccion.firebasestorage.app',
    measurementId: 'G-YX42KB37MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS3iw5cHjsFrIqYW0lXShDeXJS63pw2PM',
    appId: '1:530652435890:android:3177b0646bf3e47bb540ab',
    messagingSenderId: '530652435890',
    projectId: 'cocep-producccion',
    storageBucket: 'cocep-producccion.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF5GEni4XSLCBw11VPjC869mPXwTqU0rM',
    appId: '1:352407924529:ios:e7de50c85edadbcc0f4a10',
    messagingSenderId: '352407924529',
    projectId: 'cocep-produccion',
    storageBucket: 'cocep-produccion.firebasestorage.app',
    iosBundleId: 'com.example.churchManagementApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF5GEni4XSLCBw11VPjC869mPXwTqU0rM',
    appId: '1:352407924529:ios:e7de50c85edadbcc0f4a10',
    messagingSenderId: '352407924529',
    projectId: 'cocep-produccion',
    storageBucket: 'cocep-produccion.firebasestorage.app',
    iosBundleId: 'com.example.churchManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATfaq3XTcMku0MaI9Fc7Y04nyKLMCdxnM',
    appId: '1:352407924529:web:bdf545c7dc0473330f4a10',
    messagingSenderId: '352407924529',
    projectId: 'cocep-produccion',
    authDomain: 'cocep-produccion.firebaseapp.com',
    storageBucket: 'cocep-produccion.firebasestorage.app',
    measurementId: 'G-P8ZSNPVY5F',
  );

}